# Generated by Django 3.2 on 2021-04-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20210421_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='', max_length=10, verbose_name='Symbol'),
        ),
    ]
