# Generated by Django 3.2 on 2021-04-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(default='', max_length=5, verbose_name='Code'),
        ),
    ]
