# Generated by Django 3.2 on 2021-04-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(default='', max_length=70, verbose_name='Native Name'),
        ),
    ]
