# Generated by Django 3.2 on 2021-04-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0012_rename_native_name_language_nativename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='native_name',
            new_name='nativeName',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='numeric_code',
            new_name='numericCode',
        ),
    ]
