# Generated by Django 3.2 on 2021-04-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0014_auto_20210421_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=150, verbose_name='Capital'),
        ),
    ]
