# Generated by Django 3.2 on 2021-04-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0015_alter_country_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='numericCode',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numeric Code'),
        ),
    ]
