# Generated by Django 3.2 on 2021-04-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0016_alter_country_numericcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='cities',
            field=models.ManyToManyField(related_name='country', to='countries.City', verbose_name='City'),
        ),
    ]
